### ISSUE TITLE
Compatibility issue with VSCode veersion 1.52.1

### ISSUE THREAD

**Issue by nadzhou** [nas5w/svelte-dark#1]
here's the screenshot: 

![image](https://user-images.githubusercontent.com/25282805/108017474-cf190380-7036-11eb-95ab-3940a2d633c6.png)

my system: 
Linux 20.10
VScode 1.52.1

**Comment by nas5w** [comment]
Looking into it!

**Comment by nas5w** [comment]
@nadzhou OK, I published a new version of the package with a lower required VSCode version. Can you try installing the latest version of the extension and let me know if it works?

Thank you!

**Comment by nas5w** [comment]
I believe this is fixed. Will close now but please open a new issue if you're still having trouble.
